version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Optional configurations:
    labels:
      - "dependencies"
      - "actions"
    commit-message:
      prefix: "chore"
