#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if ! iptables -L &>/dev/null; then
    echo "[ERROR] iptables check failed. Please ensure container has NET_ADMIN capability" >&2
    sleep infinity
fi

echo "[INFO] Resetting iptables (flushing chains and deleting custom chains)"
iptables -F
iptables -X

echo "[INFO] Setting all chain policies to DROP"
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

if [[ "$(cat /proc/sys/net/ipv6/conf/all/disable_ipv6)" -eq 0 ]]; then
    echo "[WARNING] IPv6 is enabled. You should disable IPv6 in your container configuration:"
    echo "Using docker-compose.yml:"
    echo "    sysctls:"
    echo "      - net.ipv6.conf.all.disable_ipv6=1"
    echo "Or with docker run:"
    echo "    --sysctl net.ipv6.conf.all.disable_ipv6=1"
    echo "[INFO] Blocking all IPv6 traffic with ip6tables"
    ip6tables -F
    ip6tables -X
    ip6tables -P INPUT DROP
    ip6tables -P OUTPUT DROP
    ip6tables -P FORWARD DROP
fi

echo "[SUCCESS] Firewall initialized. All traffic is blocked by default"
