#!/usr/bin/with-contenv bash
# shellcheck shell=bash

iface=${INTERFACE:-eth0}

if [[ -n ${ALLOW_LIST} ]]; then
    for domain in ${ALLOW_LIST//[;,]/ }; do
        # Strip URL parts, keeping only the domain
        # e.g., https://example.com/path -> example.com
        domain=$(echo "${domain}" | sed 's/^.*:\/\///;s/\/.*$//')
        # Check if domain can be resolved
        if getent hosts "$domain" &>/dev/null; then
            echo "[INFO] Allowing direct connection to ${domain}"
            iptables -A OUTPUT -o "${iface}" -d "${domain}" -j ACCEPT
        else
            echo "[WARNING] Cannot resolve domain '${domain}' (skipped)" >&2
        fi
    done
fi
