#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo "[INFO] Initializing openresolv"
# let openresolv take control of resolv.conf
resolvconf -a control 2>/dev/null </etc/resolv.conf
resolvconf -u
echo "[SUCCESS] openresolv initialized"
