#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [ -n "$NET_LOCAL" ]; then
    # Remove surrounding quotes if they exist
    NET_LOCAL="${NET_LOCAL#\"}" # Remove leading quote
    NET_LOCAL="${NET_LOCAL%\"}" # Remove trailing quote

    for inet in ${NET_LOCAL//[;,]/ }; do
        # Look up interface associated with subnet in routing table
        iface=$(ip route get "${inet%/*}" | awk 'NR==1 {for(i=1;i<=NF;i++) if($i=="dev") print $(i+1)}')

        if [ -z "$iface" ]; then
            echo "[WARNING] No interface found in routing table for subnet ${inet} (skipped)" >&2
            continue
        fi

        echo "[INFO] Allowing inbound, outbound, and forwarded traffic for local network ${inet} on ${iface}"
        iptables -A INPUT -i "${iface}" -s "${inet}" -j ACCEPT
        iptables -A OUTPUT -o "${iface}" -d "${inet}" -j ACCEPT
        iptables -A FORWARD -i "${iface}" -s "${inet}" -j ACCEPT
        iptables -A FORWARD -i "${iface}" -d "${inet}" -j ACCEPT
    done
fi
