name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags: [ '*' ]

permissions:
  contents: read
  packages: write

concurrency:
  group: docker-image-ci-${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_type != 'tag' }}

env:
  GHCR_REPOSITORY: ghcr.io/${{ github.repository_owner }}/nordlynx

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check tag
        if: github.ref_type == 'tag'
        run: |
          if [[ ! "${GITHUB_REF_NAME}" =~ ^v[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag format. Expected: vX.Y (e.g., v1.0)" >> "${GITHUB_STEP_SUMMARY}"
            exit 1
          fi

      - name: Set variables
        id: vars
        run: |
          echo "date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "${GITHUB_OUTPUT}"
          if [[ "${GITHUB_REF_TYPE}" == tag ]]; then
            echo "version=${GITHUB_REF_NAME}" >> "${GITHUB_OUTPUT}"
            echo "tags=${GHCR_REPOSITORY}:${GITHUB_REF_NAME},${GHCR_REPOSITORY}:latest" >> "${GITHUB_OUTPUT}"
          else
            echo "version=edge-${GITHUB_SHA::8}" >> "${GITHUB_OUTPUT}"
            echo "tags=${GHCR_REPOSITORY}:edge" >> "${GITHUB_OUTPUT}"
          fi

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.vars.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ steps.vars.outputs.date }}
            VERSION=${{ steps.vars.outputs.version }}
            VCS_REF=${{ github.sha }}
