name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags: [ '*' ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check tag
        if: github.ref_type == 'tag'
        run: |
          if [[ ! $GITHUB_REF_NAME =~ ^v[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag format. Expected: vX.Y (e.g., v1.0)" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      - name: Set variables
        id: vars
        run: |
          echo "date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_OUTPUT
          echo "sha_short=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
          ghcr_ref="ghcr.io/${{ github.repository_owner }}/${{ vars.IMAGE_NAME }}"
          echo "ghcr_ref=${ghcr_ref}" >> $GITHUB_OUTPUT
          dockerhub_ref="${{ vars.DOCKERHUB_NAMESPACE }}/${{ vars.IMAGE_NAME }}"
          echo "dockerhub_ref=${dockerhub_ref}" >> $GITHUB_OUTPUT
          if [[ $GITHUB_REF_TYPE == tag ]]; then
            echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
            echo "ghcr_tags=${ghcr_ref}:${GITHUB_REF_NAME},${ghcr_ref}:latest" >> $GITHUB_OUTPUT
            echo "dockerhub_tags=${dockerhub_ref}:${GITHUB_REF_NAME},${dockerhub_ref}:latest" >> $GITHUB_OUTPUT
          else
            echo "version=edge" >> $GITHUB_OUTPUT
            echo "ghcr_tags=${ghcr_ref}:edge" >> $GITHUB_OUTPUT
            echo "dockerhub_tags=${dockerhub_ref}:edge" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.vars.outputs.ghcr_tags }},${{ steps.vars.outputs.dockerhub_tags }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_DATE=${{ steps.vars.outputs.date }}
            REPO_URL=${{ github.server_url }}/${{ github.repository }}
            VCS_REF=${{ steps.vars.outputs.sha_short }}
            VERSION=${{ steps.vars.outputs.version }}
            
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ steps.vars.outputs.dockerhub_ref }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md
